LABELS = [
    "Aglaonema",
    "Aloe Vera",
    "Apple",
    "Caladium",
    "Calathea",
    "Cassava",
    "Grape",
    "Jasmine",
    "Lili Paris",
    "Monstera Andansonii",
    "Potato",
    "Rose",
    "Sansevieria",
    "Soybean",
    "sunflower",
    "Tomato",
    "Lavender",
    "Aster", 
    "Daisy", 
    "Iris", 
    "Marigold", 
    "Orchid", 
    "Poppy"
]